In [1]:
import pandas as pd


In [2]:
data =pd.read_csv('/home/chiranjeev/Downloads/iris.csv')

In [3]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      classes
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [4]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
data

sepal_length  sepal_width  petal_length  petal_width         classes
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
5             4.6          3.4           1.4          0.3     Iris-setosa
6             5.0          3.4           1.5          0.2     Iris-setosa
7             4.4          2.9           1.4          0.2     Iris-setosa
8             4.9          3.1           1.5          0.1     Iris-setosa
9             5.4          3.7           1.5          0.2     Iris-setosa
10            4.8          3.4           1.6          0.2     Iris-setosa
11            4.8          3.0           1.4          0.1     Iris-setosa
12            4.3          3.0           1.1          0.1     Iris-setosa
13            5.8          4.0           1.2          0.2     Iris-setosa
14            5.7          4.4           1.5          0.4     Iris-setosa
15            5.4          3.9           1.3          0.4     Iris-setosa
16            5.1          3.5           1.4          0.3     Iris-setosa
17            5.7          3.8           1.7          0.3     Iris-setosa
18            5.1          3.8           1.5          0.3     Iris-setosa
19            5.4          3.4           1.7          0.2     Iris-setosa
20            5.1          3.7           1.5          0.4     Iris-setosa
21            4.6          3.6           1.0          0.2     Iris-setosa
22            5.1          3.3           1.7          0.5     Iris-setosa
23            4.8          3.4           1.9          0.2     Iris-setosa
24            5.0          3.0           1.6          0.2     Iris-setosa
25            5.0          3.4           1.6          0.4     Iris-setosa
26            5.2          3.5           1.5          0.2     Iris-setosa
27            5.2          3.4           1.4          0.2     Iris-setosa
28            4.7          3.2           1.6          0.2     Iris-setosa
29            4.8          3.1           1.6          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
120           5.6          2.8           4.9          2.0  Iris-virginica
121           7.7          2.8           6.7          2.0  Iris-virginica
122           6.3          2.7           4.9          1.8  Iris-virginica
123           6.7          3.3           5.7          2.1  Iris-virginica
124           7.2          3.2           6.0          1.8  Iris-virginica
125           6.2          2.8           4.8          1.8  Iris-virginica
126           6.1          3.0           4.9          1.8  Iris-virginica
127           6.4          2.8           5.6          2.1  Iris-virginica
128           7.2          3.0           5.8          1.6  Iris-virginica
129           7.4          2.8           6.1          1.9  Iris-virginica
130           7.9          3.8           6.4          2.0  Iris-virginica
131           6.4          2.8           5.6          2.2  Iris-virginica
132           6.3          2.8           5.1          1.5  Iris-virginica
133           6.1          2.6           5.6          1.4  Iris-virginica
134           7.7          3.0           6.1          2.3  Iris-virginica
135           6.3          3.4           5.6          2.4  Iris-virginica
136           6.4          3.1           5.5          1.8  Iris-virginica
137           6.0          3.0           4.8          1.8  Iris-virginica
138           6.9          3.1           5.4          2.1  Iris-virginica
139           6.7          3.1           5.6          2.4  Iris-virginica
140           6.9          3.1           5.1          2.3  Iris-virginica
141           5.8          2.7           5.1          1.9  Iris-virginica
142      

In [6]:
data.isnull().values.any()

False

In [7]:
data.iloc[:,0:4]

sepal_length  sepal_width  petal_length  petal_width
0             4.9          3.0           1.4          0.2
1             4.7          3.2           1.3          0.2
2             4.6          3.1           1.5          0.2
3             5.0          3.6           1.4          0.2
4             5.4          3.9           1.7          0.4
5             4.6          3.4           1.4          0.3
6             5.0          3.4           1.5          0.2
7             4.4          2.9           1.4          0.2
8             4.9          3.1           1.5          0.1
9             5.4          3.7           1.5          0.2
10            4.8          3.4           1.6          0.2
11            4.8          3.0           1.4          0.1
12            4.3          3.0           1.1          0.1
13            5.8          4.0           1.2          0.2
14            5.7          4.4           1.5          0.4
15            5.4          3.9           1.3          0.4
16            5.1          3.5           1.4          0.3
17            5.7          3.8           1.7          0.3
18            5.1          3.8           1.5          0.3
19            5.4          3.4           1.7          0.2
20            5.1          3.7           1.5          0.4
21            4.6          3.6           1.0          0.2
22            5.1          3.3           1.7          0.5
23            4.8          3.4           1.9          0.2
24            5.0          3.0           1.6          0.2
25            5.0          3.4           1.6          0.4
26            5.2          3.5           1.5          0.2
27            5.2          3.4           1.4          0.2
28            4.7          3.2           1.6          0.2
29            4.8          3.1           1.6          0.2
..            ...          ...           ...          ...
120           5.6          2.8           4.9          2.0
121           7.7          2.8           6.7          2.0
122           6.3          2.7           4.9          1.8
123           6.7          3.3           5.7          2.1
124           7.2          3.2           6.0          1.8
125           6.2          2.8           4.8          1.8
126           6.1          3.0           4.9          1.8
127           6.4          2.8           5.6          2.1
128           7.2          3.0           5.8          1.6
129           7.4          2.8           6.1          1.9
130           7.9          3.8           6.4          2.0
131           6.4          2.8           5.6          2.2
132           6.3          2.8           5.1          1.5
133           6.1          2.6           5.6          1.4
134           7.7          3.0           6.1          2.3
135           6.3          3.4           5.6          2.4
136           6.4          3.1           5.5          1.8
137           6.0          3.0           4.8          1.8
138           6.9          3.1           5.4          2.1
139           6.7          3.1           5.6          2.4
140           6.9          3.1           5.1          2.3
141           5.8          2.7           5.1          1.9
142           6.8          3.2           5.9          2.3
143           6.7          3.3           5.7          2.5
144           6.7          3.0           5.2          2.3
145           6.3          2.5           5.0          1.9
146           6.5          3.0           5.2          2.0
147           6.2          3.4           5.4          2.3
148           5.9          3.0           5.1          1.8
149           6.3          3.3           6.0          2.5

[150 rows x 4 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data.iloc[:,0:4],data['classes'],test_size=0.3)

In [9]:
x_train.shape,y_train.shape


((105, 4), (105,))

In [10]:
x_test.shape,y_test.shape

((45, 4), (45,))

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
x_train = scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)

In [12]:
x_train,x_train.shape

(array([[0.83333333, 0.375     , 0.89830508, 0.70833333],
        [0.72222222, 0.45833333, 0.74576271, 0.83333333],
        [1.        , 0.75      , 0.91525424, 0.79166667],
        [0.41666667, 0.33333333, 0.69491525, 0.95833333],
        [0.5       , 0.375     , 0.62711864, 0.54166667],
        [0.58333333, 0.33333333, 0.77966102, 0.83333333],
        [0.94444444, 0.41666667, 0.86440678, 0.91666667],
        [0.38888889, 0.33333333, 0.59322034, 0.5       ],
        [0.13888889, 0.41666667, 0.06779661, 0.        ],
        [0.52777778, 0.08333333, 0.59322034, 0.58333333],
        [0.33333333, 0.91666667, 0.06779661, 0.04166667],
        [0.08333333, 0.5       , 0.06779661, 0.04166667],
        [0.22222222, 0.625     , 0.06779661, 0.04166667],
        [0.25      , 0.29166667, 0.49152542, 0.54166667],
        [0.19444444, 0.625     , 0.05084746, 0.08333333],
        [0.41666667, 0.29166667, 0.49152542, 0.45833333],
        [0.75      , 0.5       , 0.62711864, 0.54166667],
        [0.527

In [13]:
x_test,x_test.shape

(array([[0.38888889, 0.20833333, 0.6779661 , 0.79166667],
        [0.38888889, 0.41666667, 0.54237288, 0.45833333],
        [0.66666667, 0.45833333, 0.77966102, 0.95833333],
        [0.36111111, 0.33333333, 0.66101695, 0.79166667],
        [0.41666667, 0.29166667, 0.69491525, 0.75      ],
        [0.19444444, 0.5       , 0.03389831, 0.04166667],
        [0.13888889, 0.41666667, 0.06779661, 0.08333333],
        [0.13888889, 0.58333333, 0.10169492, 0.04166667],
        [0.02777778, 0.5       , 0.05084746, 0.04166667],
        [0.22222222, 0.58333333, 0.08474576, 0.04166667],
        [0.05555556, 0.125     , 0.05084746, 0.08333333],
        [0.55555556, 0.375     , 0.77966102, 0.70833333],
        [0.5       , 0.33333333, 0.50847458, 0.5       ],
        [0.58333333, 0.33333333, 0.77966102, 0.875     ],
        [0.77777778, 0.41666667, 0.83050847, 0.83333333],
        [0.16666667, 0.45833333, 0.08474576, 0.        ],
        [0.25      , 0.625     , 0.08474576, 0.04166667],
        [0.222

In [14]:
data=pd.DataFrame(x_train)
data

0         1         2         3
0    0.833333  0.375000  0.898305  0.708333
1    0.722222  0.458333  0.745763  0.833333
2    1.000000  0.750000  0.915254  0.791667
3    0.416667  0.333333  0.694915  0.958333
4    0.500000  0.375000  0.627119  0.541667
5    0.583333  0.333333  0.779661  0.833333
6    0.944444  0.416667  0.864407  0.916667
7    0.388889  0.333333  0.593220  0.500000
8    0.138889  0.416667  0.067797  0.000000
9    0.527778  0.083333  0.593220  0.583333
10   0.333333  0.916667  0.067797  0.041667
11   0.083333  0.500000  0.067797  0.041667
12   0.222222  0.625000  0.067797  0.041667
13   0.250000  0.291667  0.491525  0.541667
14   0.194444  0.625000  0.050847  0.083333
15   0.416667  0.291667  0.491525  0.458333
16   0.750000  0.500000  0.627119  0.541667
17   0.527778  0.375000  0.559322  0.500000
18   0.555556  0.208333  0.661017  0.583333
19   0.083333  0.458333  0.084746  0.041667
20   0.388889  1.000000  0.084746  0.125000
21   0.305556  0.416667  0.593220  0.583333
22   0.916667  0.416667  0.949153  0.833333
23   0.305556  0.583333  0.118644  0.041667
24   0.083333  0.666667  0.000000  0.041667
25   0.555556  0.208333  0.677966  0.750000
26   0.861111  0.333333  0.864407  0.750000
27   0.555556  0.583333  0.779661  0.958333
28   0.027778  0.416667  0.050847  0.041667
29   0.111111  0.500000  0.050847  0.041667
..        ...       ...       ...       ...
75   0.194444  0.416667  0.101695  0.041667
76   0.388889  0.250000  0.423729  0.375000
77   0.500000  0.416667  0.610169  0.541667
78   0.472222  0.375000  0.593220  0.583333
79   0.694444  0.333333  0.644068  0.541667
80   0.333333  0.250000  0.576271  0.458333
81   0.333333  0.625000  0.050847  0.041667
82   0.138889  0.583333  0.152542  0.041667
83   0.194444  0.583333  0.101695  0.125000
84   0.000000  0.416667  0.016949  0.000000
85   0.333333  0.166667  0.474576  0.416667
86   0.138889  0.458333  0.101695  0.041667
87   0.583333  0.500000  0.593220  0.583333
88   0.722222  0.458333  0.661017  0.583333
89   0.583333  0.458333  0.762712  0.708333
90   0.277778  0.708333  0.084746  0.041667
91   0.944444  0.333333  0.966102  0.791667
92   0.194444  0.541667  0.067797  0.041667
93   0.222222  0.208333  0.338983  0.416667
94   0.611111  0.500000  0.694915  0.791667
95   0.555556  0.541667  0.627119  0.625000
96   0.694444  0.416667  0.762712  0.833333
97   0.361111  0.291667  0.542373  0.500000
98   0.555556  0.125000  0.576271  0.500000
99   0.388889  0.333333  0.525424  0.500000
100  0.416667  0.291667  0.525424  0.375000
101  0.194444  0.125000  0.389831  0.375000
102  0.333333  0.125000  0.508475  0.500000
103  0.250000  0.875000  0.084746  0.000000
104  0.638889  0.375000  0.610169  0.500000

[105 rows x 4 columns]

In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)

In [16]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [17]:
score=knn.score(x_test,y_test)
acc=score*100
print("score=",score)
print("acc=",acc)

score= 0.9555555555555556
acc= 95.55555555555556


In [18]:
y_pred=knn.predict(x_test)
y_pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype=object)

In [19]:
y_test

112     Iris-virginica
94     Iris-versicolor
139     Iris-virginica
120     Iris-virginica
141     Iris-virginica
34         Iris-setosa
44         Iris-setosa
10         Iris-setosa
41         Iris-setosa
38         Iris-setosa
40         Iris-setosa
102     Iris-virginica
70     Iris-versicolor
131     Iris-virginica
101     Iris-virginica
33         Iris-setosa
26         Iris-setosa
16         Iris-setosa
8          Iris-setosa
116     Iris-virginica
126     Iris-virginica
20         Iris-setosa
87     Iris-versicolor
100     Iris-virginica
17         Iris-setosa
119     Iris-virginica
43         Iris-setosa
144     Iris-virginica
124     Iris-virginica
84     Iris-versicolor
53     Iris-versicolor
22         Iris-setosa
91     Iris-versicolor
118     Iris-virginica
42         Iris-setosa
123     Iris-virginica
72     Iris-versicolor
6          Iris-setosa
64     Iris-versicolor
85     Iris-versicolor
60     Iris-versicolor
122     Iris-virginica
82     Iris-versicolor
143     Iri

In [20]:
y_test==y_pred


112     True
94      True
139     True
120     True
141     True
34      True
44      True
10      True
41      True
38      True
40      True
102     True
70      True
131     True
101     True
33      True
26      True
16      True
8       True
116     True
126     True
20      True
87      True
100     True
17      True
119     True
43      True
144     True
124     True
84      True
53      True
22      True
91      True
118    False
42      True
123     True
72      True
6       True
64      True
85      True
60      True
122     True
82     False
143     True
125     True
Name: classes, dtype: bool

In [21]:
import numpy as np
score_manual=(np.sum(y_pred==y_test))/(float(len(y_test)))
print(score_manual)

0.9555555555555556


In [22]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 10  1]
 [ 0  1 17]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       0.91      0.91      0.91        11
 Iris-virginica       0.94      0.94      0.94        18

      micro avg       0.96      0.96      0.96        45
      macro avg       0.95      0.95      0.95        45
   weighted avg       0.96      0.96      0.96        45



In [23]:
error=[]
for i in range(1,40):
    knn= KNeighborsClassifier(n_neighbors=i) 
    knn.fit(x_train,y_train)
    y_pred=knn.predict(x_test)
    error.append(np.mean(y_pred!=y_test))
print("error=",error)

error= [0.044444444444444446, 0.044444444444444446, 0.044444444444444446, 0.022222222222222223, 0.022222222222222223, 0.022222222222222223, 0.044444444444444446, 0.044444444444444446, 0.044444444444444446, 0.044444444444444446, 0.044444444444444446, 0.022222222222222223, 0.022222222222222223, 0.022222222222222223, 0.022222222222222223, 0.044444444444444446, 0.022222222222222223, 0.022222222222222223, 0.022222222222222223, 0.06666666666666667, 0.06666666666666667, 0.06666666666666667, 0.06666666666666667, 0.06666666666666667, 0.06666666666666667, 0.08888888888888889, 0.06666666666666667, 0.1111111111111111, 0.1111111111111111, 0.1111111111111111, 0.1111111111111111, 0.13333333333333333, 0.13333333333333333, 0.17777777777777778, 0.17777777777777778, 0.17777777777777778, 0.17777777777777778, 0.17777777777777778, 0.17777777777777778]


In [24]:

""""
import matplotlib.pyplot as plt
plt.figure(figsize=(12, 6))  
plt.plot(range(1, 40), error, color='red', linestyle='dashed', marker='o',markerfacecolor='green', markersize=7)
plt.title('Error Rate vs K Value')  
plt.xlabel('K Value')  
plt.ylabel('Mean Error')  
"""

'"\nimport matplotlib.pyplot as plt\nplt.figure(figsize=(12, 6))  \nplt.plot(range(1, 40), error, color=\'red\', linestyle=\'dashed\', marker=\'o\',markerfacecolor=\'green\', markersize=7)\nplt.title(\'Error Rate vs K Value\')  \nplt.xlabel(\'K Value\')  \nplt.ylabel(\'Mean Error\')  \n'

In [25]:
from sklearn.naive_bayes import GaussianNB
clf=GaussianNB()
clf.fit(x_train,y_train)
score=clf.score(x_test,y_test)
print("score=",score)


score= 0.9777777777777777


In [26]:
clf.predict(x_test)

array(['Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [27]:
y_test==y_pred

112    False
94      True
139     True
120    False
141    False
34      True
44      True
10      True
41      True
38      True
40      True
102     True
70      True
131     True
101     True
33      True
26      True
16      True
8       True
116     True
126    False
20      True
87      True
100    False
17      True
119     True
43      True
144     True
124     True
84      True
53      True
22      True
91      True
118    False
42      True
123     True
72      True
6       True
64      True
85      True
60      True
122    False
82      True
143     True
125    False
Name: classes, dtype: bool

In [28]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 11  8]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.58      0.73        19
 Iris-virginica       0.56      1.00      0.71        10

      micro avg       0.82      0.82      0.82        45
      macro avg       0.85      0.86      0.82        45
   weighted avg       0.90      0.82      0.82        45

